### ISSUE TITLE
Reference Tag by Path

### ISSUE THREAD

**Issue by cynthiahhc** [marko-js/tags#12]
### Description

Add a reference tag by path when referencing a context.

### Why

Some marko templates do not have a specific names which might just be `index.marko`. There is no way to reference it.

**Comment by ccinelli** [comment]
I think the context should have and optional `name` attribute that can be used as key instead of the  component name.

**Comment by DylanPiercey** [comment]
This is now possible since you can pass in the component constructor, eg:

```
import SomeComponent from "./some-path.marko";

<context|| from=someComponent>
  ...
```
