### ISSUE TITLE
<context> - Separate context in 2 tags

### ISSUE THREAD

**Issue by ccinelli** [marko-js/tags#14]
### Description
How to use of `<context>` is not intuitive.
I think that splitting it in 2 tags would add clarity: 
 
1. `<context-provider>` or `<set-context>` 
2. `<context-consumer>` or `<get-context>` 
 
### Why

Because people should not define attributes as they are getting attributes. This kind of syntax make clear if we are defining a context or if we are consuming it. 

### Possible Implementation & Open Questions

The separation is almost there in the helper.

**Comment by DylanPiercey** [comment]
The [tags api preview](https://github.com/marko-js/tags-api-preview) now does this.
